hmc/hmk/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, g, redirect, url_for, request, session, flash
from functools import wraps
from hmc.models import BDUser, BDRecord
from hmc.database import db
import uuid
import datetime
from sqlalchemy import desc

hmk_bp = Blueprint('hmk', __name__)

@hmk_bp.route('/reg/', methods=['GET', 'POST'])
def reg():
    if request.method == 'POST':
        username = request.form['username']
        password_md5 = request.form['password_md5']
        nickname = request.form['nickname']
        comname = request.form['comname']
        if BDUser.query.filter_by(username=username).count():
            flash('Username already exist')
            return redirect(url_for('hmk.reg'))
        else:
            u = BDUser(username=username, password_md5=password_md5, nickname=nickname, comname=comname)
            db.session.add(u)
            db.session.commit()
            session['logged_in'] = True
            session['username'] = username
            session['nickname'] = nickname
            session['comname'] = comname
            flash('You were logged in')
            return redirect(url_for('hmk.index'))
        return redirect(url_for('hmk.index'))
    else:
        return render_template('hmk/reg.html')
    
@hmk_bp.route('/logout/')
def logout():
    session.pop('logged_in', None)
    session.pop('username', None)
    session.pop('nickname', None)
    session.pop('comname', None)
    return redirect(url_for('hmk.index'))

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
#         if g.user is None:
        if not session.get('logged_in'):
            return redirect(url_for('hmk.login', next=request.url))
        return f(*args, **kwargs)
    return decorated_function

@hmk_bp.route('/login/', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password_md5 = request.form['password_md5']
        u = BDUser.query.filter_by(username=username, password_md5=password_md5).first()
        if u:
            session['logged_in'] = True
            session['username'] = username
            session['nickname'] = u.nickname
            session['comname'] = u.comname
            flash('You were logged in')
            return redirect(url_for('hmk.index'))
        else:
            flash('Login failed')
            return redirect(url_for('hmk.login'))
    else:
        return render_template('hmk/login.html')
    
@hmk_bp.route('/')
@hmk_bp.route('/index/')
def index():
    return render_template('hmk/index.html')

@hmk_bp.route('/add/', methods=['GET', 'POST'])
@login_required
def add():
    if request.method == 'POST':
        merchant_name = request.form['merchant_name']
        merchant_tel = request.form['merchant_tel']
        visit_purpose = request.form['visit_purpose']
        if visit_purpose == 'wh':
            visit_purpose = '维护'
        elif visit_purpose == 'qy':
            visit_purpose = '签约'
        else:
            visit_purpose = '挖掘需求'
        visit_result = request.form['visit_result']
        visit_time = request.form['visit_time']
        bd_username=session.get('username')
        record_id = str(uuid.uuid1())
        record = BDRecord(record_id=record_id, bd_username=bd_username, merchant_name=merchant_name, merchant_tel=merchant_tel, \
                          visit_purpose=visit_purpose, visit_result=visit_result, visit_time=visit_time)
        db.session.add(record)
        db.session.commit()
        flash('Add succeed.')
        return redirect(url_for('hmk.add'))    
    else:
        return render_template('hmk/add.html')

@hmk_bp.route('/view/')
@login_required
def view():
    limit = int(request.values.get('limit', default=7))    #默认获取7天的数据
    print limit
    if limit in [3, 7]:
        some_days_ago = str((datetime.datetime.now() - datetime.timedelta(days = limit)).strftime("%Y-%m-%d"))
        records = BDRecord.query.filter_by(bd_username=session.get('username')).filter(BDRecord.visit_time >= some_days_ago).order_by(desc(BDRecord.visit_time)).all()
    else:   #返回所有数据
        records = BDRecord.query.filter_by(bd_username=session.get('username')).order_by(desc(BDRecord.visit_time)).all()
    return render_template('hmk/view.html', records=records)




hmc/templates/hmk/add.html
{% extends "layout.html" %}
{% block title %}Add{% endblock %}
{% block js %}
<script type="text/javascript">
window.onload = function(){
    	var d = document.getElementById('form_date_element');
   	 	var now = new Date();
   	 	year = now.getFullYear();
   	 	month = now.getMonth() + 1;
		day = now.getDate();
   	 	if(month < 10 ){
   	 		month = '0' + String(month);
   	 	}
   	 	if(day < 10 ){
   	 		day = '0' + String(day);
   	 	}
    	date = year + '-' + month + '-' + day;
    	d.value = date;
  	}
	function checkForm(form) { 
	    for (var i = 0; i < form.elements.length; i++) { 
	        if (form.elements[i].type == "text" && form.elements[i].value == "") { 
	            alert("Fill out ALL fields."); 
	            return false; 
	        } 
	    } 
	    return true; 
	} 
</script>
{% endblock %}
{% block body %}
<div class="metanav">
    {% if not session.logged_in %}
        <a href="{{ url_for('hmk.login') }}">log in</a>
    {% else %}
        <a>欢迎您, {{ session.nickname }} !</a>
        <a href="{{ url_for('hmk.logout') }}">log out</a>
        <h1><a href="{{ url_for('hmk.view') }}">view</a></h1>
    {% endif %}
</div>
<div >
    <form action="{{ url_for('hmk.add') }}" method="post" onsubmit="return checkForm(this)">
      <dl>
        <dt>拜访商户名称:
        <dd><input type="text" size="30" name="merchant_name">
        <dt>商户负责人电话:
        <dd><input type="text" size="30" name="merchant_tel">
        <dt>拜访目的:
        <dd><input type="radio" name="visit_purpose" value="wjxq" checked>挖掘需求
        <dd><input type="radio" name="visit_purpose" value="qy">签约
        <dd><input type="radio" name="visit_purpose" value="wh">维护
        <dt>拜访结果:
        <dd><textarea name="visit_result" rows="5" cols="40"></textarea>
        <dt>拜访时间:
        <dd><input type="date" value="" id="form_date_element" name="visit_time">
        <br>
        <br>
        <dd><button type="submit">Add</button>
      </dl>
    </form>
</div>
{% endblock %}

hmc/templates/hmk/index.html
{% extends "layout.html" %}
{% block title %}Index{% endblock %}
{% block body %}
<div class="metanav">
    {% if not session.logged_in %}
        <a href="{{ url_for('hmk.login') }}">log in</a>
    {% else %}
        <a>欢迎您, {{ session.nickname }} !</a>
        <a href="{{ url_for('hmk.logout') }}">log out</a>
    {% endif %}
</div>
<div >
	<h2><a href="{{ url_for('hmk.add') }}">Add</a></h2>
	<h2><a href="{{ url_for('hmk.view') }}">View</a></h2>
</div>
{% endblock %}

hmc/templates/hmk/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block js %}
  <script type="text/javascript" src="{{ url_for('static', filename='js/md5.min.js')  }}" ></script>
  <script type="text/javascript">
    function toMd5() {
      var input_pw = document.getElementById('password');
      var password_md5 = document.getElementById('password_md5');
      password_md5.value = md5(input_pw.value);
      return true;
    }
  </script>
{% endblock %}
{% block body %}
  <div class="metanav">
      <a href="{{ url_for('hmk.reg') }}">Register</a>
  </div>
  <h2>Login</h2>
  {% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('hmk.login') }}" method="post" onsubmit="return toMd5()">
      <p>账号：<input type="text" name="username"></p>
      <p>密码：<input type="password" id="password"></p>
      <p><input type="hidden" id="password_md5" name="password_md5"></p>
      <p><button type="submit">登陆</button></p>
  </form>
{% endblock %}

hmc/templates/hmk/reg.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}
{% block js %}
	<script type="text/javascript" src="{{ url_for('static', filename='js/md5.min.js')  }}" ></script>
	<script type="text/javascript">
		function checkRegisterForm() {
			var usernameReg = /[0-9a-zA-Z_]{6,10}/;
			var passwordReg = /\w{6,20}/;
			var input_un = document.getElementById('username');
			var input_pw = document.getElementById('password');
			var input_pw2 = document.getElementById('password-2');
			var password_md5 = document.getElementById('password_md5');

			if(!usernameReg.test(input_un.value)){
			 alert('账号必须为6-10位的英文字母或数字');
			 return false;
			}
			if(!passwordReg.test(input_pw.value)){
			 alert('密码必须是6-20位字母或数字');
			 return false;
			}
			if(input_pw.value != input_pw.value){
			 alert('两次输入的口令必须一致');
			 return false;
			}
			password_md5.value = md5(input_pw.value);
			return true;
		}
	</script>
{% endblock %}
{% block body %}
<div class="metanav">
    <a href="{{ url_for('hmk.login') }}">Login</a>
</div>
<h2>Register</h2>
{% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
<div >
	<form id="register" method="post" action="{{ url_for('hmk.reg') }}" onsubmit="return checkRegisterForm()">
	    <p id="test-error" style="color:red"></p>
	    <p>
	        账号: <input type="text" id="username" name="username">
	    </p>
	    <p>
		    昵称：<input type="text" id="nickname" name="nickname">
	    </p> 
	    <p>
		    公司名称：<input type="text" id="comname" name="comname">
	    </p> 
	    <p>
	        口令: <input type="password" id="password">
	    </p>
	    <p>
	        重复口令: <input type="password" id="password-2">
	    </p>
	    <input type="hidden" id="password_md5" name="password_md5">
	    <p>
	        <button type="reset">重置</button> <button type="submit">注册</button> 
	    </p>
	</form>
</div>
{% endblock %}

hmc/templates/hmk/view.html
{% extends "layout.html" %}
{% block title %}View{% endblock %}
{% block body %}
<div class="metanav">
    {% if not session.logged_in %}
        <a href="{{ url_for('hmk.login') }}">log in</a>
    {% else %}
        <a>欢迎您, {{ session.nickname }} !</a>
        <a href="{{ url_for('hmk.logout') }}">log out</a>
        <h1><a href="{{ url_for('hmk.add') }}">add</a></h1>
    {% endif %}
</div>
<div >
  <a href="{{ url_for('hmk.view', limit=3) }}">最近3天</a>
  <a href="{{ url_for('hmk.view', limit=7) }}">最近7天</a>
  <a href="{{ url_for('hmk.view', limit=999) }}">所有</a>
  <ul class="records">
	  {% for record in records %}
	  	<hr>
	    <li><h2>商户名称：{{ record.merchant_name }}</h2></li>
	    <li>拜访时间：{{ record.visit_time }}</li>
	    <li>负责人电话：{{ record.merchant_tel }}</li>
	    <li>拜访目的：{{ record.visit_purpose }}</li>
	    <li>拜访结果：{{ record.visit_result }}</li>
	  {% else %}
	    <li><em>No records here so far</em></li>
	  {% endfor %}
  </ul>
</div>
{% endblock %}