hmc/home/forms.py
# -*- coding: utf-8 -*-
from flask_wtf import FlaskForm
from wtforms import StringField, BooleanField, PasswordField
from wtforms.validators import DataRequired


hmc/home/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, render_template, g, request, session, flash, redirect, url_for
from hmc.models import User
from hmc.database import db

#from flask_login import login_required
home_bp = Blueprint('home', __name__)

@home_bp.route('/')
@home_bp.route('/index')
def index():
    return render_template('home/index.html')

@home_bp.route('/reg', methods=['GET', 'POST'])
def reg():
    if request.method == 'POST':
        username = request.form['username']
        password_md5 = request.form['password_md5']
        nickname = request.form['nickname']
        
        if User.query.filter_by(username=username).count():
            flash('Username already exist')
            return redirect(url_for('home.reg'))
        else:
            u = User(username=username, password_md5=password_md5, nickname=nickname)
            db.session.add(u)
            db.session.commit()
            session['logged_in'] = True
            session['nickname'] = nickname
            flash('You were logged in')
            return redirect(url_for('home.index'))
        return redirect(url_for('home.index'))
    else:
        return render_template('home/reg.html')

@home_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password_md5 = request.form['password_md5']
        u = User.query.filter_by(username=username, password_md5=password_md5).first()
        if u:
            session['logged_in'] = True
            session['nickname'] = u.nickname
            flash('You were logged in')
            return redirect(url_for('home.index'))
        else:
            flash('Login failed')
            return redirect(url_for('home.login'))
    else:
        return render_template('home/login.html')

@home_bp.route('/logout')
def logout():
    session.pop('logged_in', None)
    session.pop('nickname', None)
    return redirect(url_for('home.index'))

@home_bp.route('/test')
def test():
    return 'test'

@home_bp.route('/test2')
def test2():
    return 'test2'

hmc/templates/home/index.html
{% extends 'layout.html' %}
{% block css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/puzzle_game/style.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/puzzle_game/puzzle.css') }}">
{% endblock %}

{% block js %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/puzzle_game/jquery-ui.js')  }}" ></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/puzzle_game/puzzle.js')  }}" ></script>
{% endblock %}

{% block body %}
<div class="metanav">
    {% if not session.logged_in %}
        <a href="{{ url_for('home.login') }}">log in</a>
    {% else %}
        <a>欢迎您, {{ session.nickname }} !</a>
        <a href="{{ url_for('home.logout') }}">log out</a>
    {% endif %}
</div>
<body style="cursor: auto;">
    <div id="collage">
        <div id="playPanel" style="padding: 5px;">
            <h3 id="imgTitle">
                Qutub Minar</h3>
            <hr>
            <div style="display: inline-block; margin: auto; width: 100%; vertical-align: top;">
                <ul id="sortable" class="sortable">
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="0" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 0% 0%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="1" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 33.33% 0%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="2" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 66.66% 0%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="3" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 99.99% 0%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="4" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 0% 33.33%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="5" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 33.33% 33.33%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="6" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 66.66% 33.33%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="7" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 99.99% 33.33%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="8" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 0% 66.66%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="9" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 33.33% 66.66%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="10" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 66.66% 66.66%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="11" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 99.99% 66.66%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="12" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 0% 99.99%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="13" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 33.33% 99.99%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="14" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 66.66% 99.99%;"></li>
                    <li class="item ui-draggable ui-draggable-handle ui-droppable" data-value="15" style="background-image: {{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}};
                        background-position: 99.99% 99.99%;"></li>
                </ul>
               <div id="actualImageBox" >
                    <!--                     
                        <img id="actualImage" src="{{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}}"> 
                        <div>
                            Re arrange to create a picture like this at left side.
                        </div>
                        <br>
                    -->
                    <div>
                        <button id="newPhoto" type="button" class="btn">
                            Another Photo</button>
                    </div>
                </div>
            </div>
        </div>
        <div id="gameOver" style="display: none;">
            <div style="background-color: #fc9e9e; padding: 5px 10px 20px 10px; text-align: center;">
                <h2 style="text-align: center">
                    Game Over!!</h2>
                Congratulations!!
                <br>
                <br>
                You have completed this picture.
                <br>
                <br>
                <div>
                    <button type="button" onclick="window.location.reload(true);">
                        Play Again</button>
                </div>
            </div>
        </div>
        <script>
            var images = [
                { src: "{{ url_for('static', filename='images/puzzle_game/london-bridge.jpg')}}", title: 'London Bridge' },
                { src: "{{ url_for('static', filename='images/puzzle_game/lotus-temple.jpg')}}", title: 'Lotus Temple' },
                { src: "{{ url_for('static', filename='images/puzzle_game/qutub-minar.jpg')}}", title: 'Qutub Minar' },
                { src: "{{ url_for('static', filename='images/puzzle_game/statue-of-liberty.jpg')}}", title: 'Statue Of Liberty' },
                { src: "{{ url_for('static', filename='images/puzzle_game/taj-mahal.jpg')}}", title: 'Taj Mahal' },
                { src: "{{ url_for('static', filename='images/puzzle_game/shuai-bi.jpg')}}", title: 'Shuai Bi' },
                { src: "{{ url_for('static', filename='images/puzzle_game/we-chat.jpg')}}", title: 'We Chat' }
            ];

            $(function () {
                imagePuzzle.startGame(images);
                $('#newPhoto').click(function () {
                    imagePuzzle.startGame(images);
                });
            });
            
        </script>
    </div>
</body>
{% endblock %}
{% block bottom %}
    <a>相关链接:</a><br>
    <a href="http://blog.csdn.net/feifanhanmc">blog</a>
    <a href="http://github.com/feifanhanmc">github</a>
    <a href="{{ url_for('test.upload') }}">imageslim</a>
    <a href="{{ url_for('home.test') }}">test</a>
{% endblock %}

hmc/templates/home/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block js %}
  <script type="text/javascript" src="{{ url_for('static', filename='js/md5.min.js')  }}" ></script>
  <script type="text/javascript">
    function toMd5() {
      var input_pw = document.getElementById('password');
      var password_md5 = document.getElementById('password_md5');
      password_md5.value = md5(input_pw.value);
      return true;
    }
  </script>
{% endblock %}
{% block body %}
  <div class="metanav">
      <a href="{{ url_for('home.reg') }}">Register</a>
  </div>
  <h2>Login</h2>
  {% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
  <form action="{{ url_for('home.login') }}" method="post" onsubmit="return toMd5()">
      <p>账号：<input type="text" name="username"></p>
      <p>密码：<input type="password" id="password"></p>
      <p><input type="hidden" id="password_md5" name="password_md5"></p>
      <p><button type="submit">登陆</button></p>
  </form>
{% endblock %}

hmc/templates/home/reg.html
{% extends 'layout.html' %}
{% block title %}Register{% endblock %}
{% block js %}
	<script type="text/javascript" src="{{ url_for('static', filename='js/md5.min.js')  }}" ></script>
	<script type="text/javascript">
		function checkRegisterForm() {
			var usernameReg = /[0-9a-zA-Z_]{6,10}/;
			var passwordReg = /\w{6,20}/;
			var input_un = document.getElementById('username');
			var input_pw = document.getElementById('password');
			var input_pw2 = document.getElementById('password-2');
			var password_md5 = document.getElementById('password_md5');

			if(!usernameReg.test(input_un.value)){
			 alert('账号必须为6-10位的英文字母或数字');
			 return false;
			}
			if(!passwordReg.test(input_pw.value)){
			 alert('密码必须是6-20位字母或数字');
			 return false;
			}
			if(input_pw.value != input_pw.value){
			 alert('两次输入的口令必须一致');
			 return false;
			}
			password_md5.value = md5(input_pw.value);
			return true;
		}
	</script>
{% endblock %}
{% block body %}
<div class="metanav">
    <a href="{{ url_for('home.login') }}">Login</a>
</div>
<h2>Register</h2>
{% if error %}<p class="error"><strong>Error:</strong> {{ error }}{% endif %}
<div >
	<form id="register" method="post" action="{{ url_for('home.reg') }}" onsubmit="return checkRegisterForm()">
	    <p id="test-error" style="color:red"></p>
	    <p>
	        账号: <input type="text" id="username" name="username">
	    </p>
	    <p>
		    昵称：<input type="text" id="nickname" name="nickname">
	    </p> 
	    <p>
	        口令: <input type="password" id="password">
	    </p>
	    <p>
	        重复口令: <input type="password" id="password-2">
	    </p>
	    <input type="hidden" id="password_md5" name="password_md5">
	    <p>
	        <button type="reset">重置</button> <button type="submit">注册</button> 
	    </p>
	</form>
</div>
{% endblock %}